version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '5001:5001'

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true