name: Format code on push with Black

on:
  push:
    paths:
      - './backend/api.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable